### PR TITLE
add virtual carousel device

### PR DESCRIPTION
**Pull request by edaniszewski**
This PR:
- adds a virtual carousel device which reports on position, state (can it be written to), and status (is it rotating) and allows writing position.

### CODE REVIEW

**Comment by edaniszewski** [comment]
good point. I think I'm going to have to remove gometalinter from here as it doesn't seem to be happy when run in CI anymore.. the `--vendor` flag is set to ignore vendored dependencies, but it is still clearly trying to lint things in the vendor directory..

**Comment by edaniszewski** [comment]
different CI issue during snapshot build now: 


> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: ...: dial unix /var/run/docker.sock: connect: permission denied

**Comment by lazypower** [comment]
ah.. this is running quite the old pipeline

>   agent any

Maybe we don't fix the ci issues here polluting this pr. I should be able to take a swing at it tomorrow if not later today.

**Comment by edaniszewski** [comment]
@lazypower the v3 pipeline was refactored.. the stuff in master is still pretty dated. I don't *think* its a dep issue since it is getting past the lint stage and stuff. seems like an issue with how docker is made available, which I think is just a result of it being an old pipeline

**Comment by lazypower** [comment]
Thats likely too. ack.

**Comment by edaniszewski** [comment]
note: CI has been updated and is now passing. its not pretty, but since this will be relatively short-lived, as the v3 branch will get merged in soonish, I think its fine.

**Pull request merged**
