### PR TITLE
WIP - [Pipeline] - Add GoReleaser config

### PR DESCRIPTION
**Pull request by lazypower**
This is incomplete and a WIP. Most of the release process appears to be
represented into goreleaser.yaml now.

- Generates multi-arch bins
- Generates checksum digest
- Generates release as Draft, requiring human action to release. Can be
toggled to auto-release.
- Modifies the docker file to copy the binary generated by goreleaser

TODO:

- Update pipeline to use goreleaser
- if we use goreleaser in a can, we're missing make so either new image
derivative, or remove make. Either/or.

### CODE REVIEW

**Comment by edaniszewski** [comment]
The initial config/setup looks pretty rad to me. I added a commit which tackled some of the TODOs and a few other updates, namely:
* updating the Jenkins pipeline to use GoReleaser
* cleaning up the previous release scripts/targets
* updating the dev flow to work with the new image build process
* standardize some of the build args and build artifact names
* update the version in prep for this to be merged and to test the pipeline

It'll probably take a little tinkering around to get it right, but it'll probably need to be an iterative process since goreleaser basically won't work completely unless there is an actual tag (afaik)


Looks like theres some work I need to do with fixing up the jenkins pipeline still..

**Comment by edaniszewski** [comment]
So, this "works" for now, but it will not work on release just yet. For goreleaser to work as we want it to, we need both a go environment to build the release, and docker to build/push the image. Short of doing some docker-in-docker type stuff, the easiest way to get this done is installing go (>=1.11) and the latest version of goreleaser on the build node(s) themselves. 

If we do that, a lot of the janky dockerized build setups that are found in this jenkins config can also be greatly simplified.

we could also not do docker builds/pushes via goreleaser and to that as a separate stage, but one of the whole points of moving to goreleaser was to simplify and consolidate all of the various build and release steps.

**Comment by lazypower** [comment]
I'm thinking we should probably close this pr, extract the good bits we want to keep, and re-attempt this migration.

**Comment by edaniszewski** [comment]
@lazypower sounds fair. the failed release flow in this repo is creating some issues for the synse-server image build (since it pulls the latest release asset for the image with the built-in emulator), so we shouldn't set this aside for too long

(related failure in: https://github.com/vapor-ware/synse-server/pull/296)

**Comment by lazypower** [comment]
Ok. I'll take another stab at this once I've got the production cve updates rolled out.

**Pull request closed without merging**
